"""empty message

Revision ID: 8f0890fef859
Revises: 7f667c931081
Create Date: 2019-11-01 13:15:18.970541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0890fef859'
down_revision = '7f667c931081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=500), nullable=False),
    sa.Column('session_token', sa.String(length=500), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_anonymous_session_id'), 'anonymous', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_session_id'), table_name='anonymous')
    op.drop_table('anonymous')
    # ### end Alembic commands ###
